package com.healthhelper.dao;

import com.healthhelper.pojo.Archive;
import java.util.List;

public interface ArchiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table healthhelper_archive
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table healthhelper_archive
     *
     * @mbg.generated
     */
    int insert(Archive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table healthhelper_archive
     *
     * @mbg.generated
     */
    Archive selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table healthhelper_archive
     *
     * @mbg.generated
     */
    List<Archive> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table healthhelper_archive
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Archive record);
}