package com.healthhelper.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Archive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.blood
     *
     * @mbg.generated
     */
    private String blood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.height
     *
     * @mbg.generated
     */
    private BigDecimal height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.weight
     *
     * @mbg.generated
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.waist_size
     *
     * @mbg.generated
     */
    private BigDecimal waistSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.medicine
     *
     * @mbg.generated
     */
    private String medicine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.past_illness
     *
     * @mbg.generated
     */
    private String pastIllness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.family_illness
     *
     * @mbg.generated
     */
    private String familyIllness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.disability
     *
     * @mbg.generated
     */
    private String disability;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.intolerance
     *
     * @mbg.generated
     */
    private String intolerance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.meal_rule
     *
     * @mbg.generated
     */
    private String mealRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.taste
     *
     * @mbg.generated
     */
    private String taste;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.meat_vegetables
     *
     * @mbg.generated
     */
    private String meatVegetables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.smoke
     *
     * @mbg.generated
     */
    private String smoke;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.drink
     *
     * @mbg.generated
     */
    private String drink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.creat_time
     *
     * @mbg.generated
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_archive.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.id
     *
     * @return the value of healthhelper_archive.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.id
     *
     * @param id the value for healthhelper_archive.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.user_id
     *
     * @return the value of healthhelper_archive.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.user_id
     *
     * @param userId the value for healthhelper_archive.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.birthday
     *
     * @return the value of healthhelper_archive.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.birthday
     *
     * @param birthday the value for healthhelper_archive.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.blood
     *
     * @return the value of healthhelper_archive.blood
     *
     * @mbg.generated
     */
    public String getBlood() {
        return blood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.blood
     *
     * @param blood the value for healthhelper_archive.blood
     *
     * @mbg.generated
     */
    public void setBlood(String blood) {
        this.blood = blood == null ? null : blood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.height
     *
     * @return the value of healthhelper_archive.height
     *
     * @mbg.generated
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.height
     *
     * @param height the value for healthhelper_archive.height
     *
     * @mbg.generated
     */
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.weight
     *
     * @return the value of healthhelper_archive.weight
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.weight
     *
     * @param weight the value for healthhelper_archive.weight
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.waist_size
     *
     * @return the value of healthhelper_archive.waist_size
     *
     * @mbg.generated
     */
    public BigDecimal getWaistSize() {
        return waistSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.waist_size
     *
     * @param waistSize the value for healthhelper_archive.waist_size
     *
     * @mbg.generated
     */
    public void setWaistSize(BigDecimal waistSize) {
        this.waistSize = waistSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.medicine
     *
     * @return the value of healthhelper_archive.medicine
     *
     * @mbg.generated
     */
    public String getMedicine() {
        return medicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.medicine
     *
     * @param medicine the value for healthhelper_archive.medicine
     *
     * @mbg.generated
     */
    public void setMedicine(String medicine) {
        this.medicine = medicine == null ? null : medicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.past_illness
     *
     * @return the value of healthhelper_archive.past_illness
     *
     * @mbg.generated
     */
    public String getPastIllness() {
        return pastIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.past_illness
     *
     * @param pastIllness the value for healthhelper_archive.past_illness
     *
     * @mbg.generated
     */
    public void setPastIllness(String pastIllness) {
        this.pastIllness = pastIllness == null ? null : pastIllness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.family_illness
     *
     * @return the value of healthhelper_archive.family_illness
     *
     * @mbg.generated
     */
    public String getFamilyIllness() {
        return familyIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.family_illness
     *
     * @param familyIllness the value for healthhelper_archive.family_illness
     *
     * @mbg.generated
     */
    public void setFamilyIllness(String familyIllness) {
        this.familyIllness = familyIllness == null ? null : familyIllness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.disability
     *
     * @return the value of healthhelper_archive.disability
     *
     * @mbg.generated
     */
    public String getDisability() {
        return disability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.disability
     *
     * @param disability the value for healthhelper_archive.disability
     *
     * @mbg.generated
     */
    public void setDisability(String disability) {
        this.disability = disability == null ? null : disability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.intolerance
     *
     * @return the value of healthhelper_archive.intolerance
     *
     * @mbg.generated
     */
    public String getIntolerance() {
        return intolerance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.intolerance
     *
     * @param intolerance the value for healthhelper_archive.intolerance
     *
     * @mbg.generated
     */
    public void setIntolerance(String intolerance) {
        this.intolerance = intolerance == null ? null : intolerance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.meal_rule
     *
     * @return the value of healthhelper_archive.meal_rule
     *
     * @mbg.generated
     */
    public String getMealRule() {
        return mealRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.meal_rule
     *
     * @param mealRule the value for healthhelper_archive.meal_rule
     *
     * @mbg.generated
     */
    public void setMealRule(String mealRule) {
        this.mealRule = mealRule == null ? null : mealRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.taste
     *
     * @return the value of healthhelper_archive.taste
     *
     * @mbg.generated
     */
    public String getTaste() {
        return taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.taste
     *
     * @param taste the value for healthhelper_archive.taste
     *
     * @mbg.generated
     */
    public void setTaste(String taste) {
        this.taste = taste == null ? null : taste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.meat_vegetables
     *
     * @return the value of healthhelper_archive.meat_vegetables
     *
     * @mbg.generated
     */
    public String getMeatVegetables() {
        return meatVegetables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.meat_vegetables
     *
     * @param meatVegetables the value for healthhelper_archive.meat_vegetables
     *
     * @mbg.generated
     */
    public void setMeatVegetables(String meatVegetables) {
        this.meatVegetables = meatVegetables == null ? null : meatVegetables.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.smoke
     *
     * @return the value of healthhelper_archive.smoke
     *
     * @mbg.generated
     */
    public String getSmoke() {
        return smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.smoke
     *
     * @param smoke the value for healthhelper_archive.smoke
     *
     * @mbg.generated
     */
    public void setSmoke(String smoke) {
        this.smoke = smoke == null ? null : smoke.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.drink
     *
     * @return the value of healthhelper_archive.drink
     *
     * @mbg.generated
     */
    public String getDrink() {
        return drink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.drink
     *
     * @param drink the value for healthhelper_archive.drink
     *
     * @mbg.generated
     */
    public void setDrink(String drink) {
        this.drink = drink == null ? null : drink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.creat_time
     *
     * @return the value of healthhelper_archive.creat_time
     *
     * @mbg.generated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.creat_time
     *
     * @param creatTime the value for healthhelper_archive.creat_time
     *
     * @mbg.generated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_archive.update_time
     *
     * @return the value of healthhelper_archive.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_archive.update_time
     *
     * @param updateTime the value for healthhelper_archive.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}