package com.healthhelper.pojo;

import java.util.Date;

public class Sleep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.sleep_start_time
     *
     * @mbg.generated
     */
    private String sleepStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.sleep_end_time
     *
     * @mbg.generated
     */
    private String sleepEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.sleep_total_time
     *
     * @mbg.generated
     */
    private String sleepTotalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.sleep_condition
     *
     * @mbg.generated
     */
    private String sleepCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.creat_time
     *
     * @mbg.generated
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column healthhelper_sleep.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.id
     *
     * @return the value of healthhelper_sleep.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.id
     *
     * @param id the value for healthhelper_sleep.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.user_id
     *
     * @return the value of healthhelper_sleep.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.user_id
     *
     * @param userId the value for healthhelper_sleep.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.sleep_start_time
     *
     * @return the value of healthhelper_sleep.sleep_start_time
     *
     * @mbg.generated
     */
    public String getSleepStartTime() {
        return sleepStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.sleep_start_time
     *
     * @param sleepStartTime the value for healthhelper_sleep.sleep_start_time
     *
     * @mbg.generated
     */
    public void setSleepStartTime(String sleepStartTime) {
        this.sleepStartTime = sleepStartTime == null ? null : sleepStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.sleep_end_time
     *
     * @return the value of healthhelper_sleep.sleep_end_time
     *
     * @mbg.generated
     */
    public String getSleepEndTime() {
        return sleepEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.sleep_end_time
     *
     * @param sleepEndTime the value for healthhelper_sleep.sleep_end_time
     *
     * @mbg.generated
     */
    public void setSleepEndTime(String sleepEndTime) {
        this.sleepEndTime = sleepEndTime == null ? null : sleepEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.sleep_total_time
     *
     * @return the value of healthhelper_sleep.sleep_total_time
     *
     * @mbg.generated
     */
    public String getSleepTotalTime() {
        return sleepTotalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.sleep_total_time
     *
     * @param sleepTotalTime the value for healthhelper_sleep.sleep_total_time
     *
     * @mbg.generated
     */
    public void setSleepTotalTime(String sleepTotalTime) {
        this.sleepTotalTime = sleepTotalTime == null ? null : sleepTotalTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.sleep_condition
     *
     * @return the value of healthhelper_sleep.sleep_condition
     *
     * @mbg.generated
     */
    public String getSleepCondition() {
        return sleepCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.sleep_condition
     *
     * @param sleepCondition the value for healthhelper_sleep.sleep_condition
     *
     * @mbg.generated
     */
    public void setSleepCondition(String sleepCondition) {
        this.sleepCondition = sleepCondition == null ? null : sleepCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.creat_time
     *
     * @return the value of healthhelper_sleep.creat_time
     *
     * @mbg.generated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.creat_time
     *
     * @param creatTime the value for healthhelper_sleep.creat_time
     *
     * @mbg.generated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column healthhelper_sleep.update_time
     *
     * @return the value of healthhelper_sleep.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column healthhelper_sleep.update_time
     *
     * @param updateTime the value for healthhelper_sleep.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}